
-- Create exercises table
create table if not exists exercises (
  id text primary key,
  name text not null,
  equipment text not null,
  category text not null,
  muscle_group text not null,
  gif_url text
);

-- Enable RLS (Public Read)
alter table exercises enable row level security;

do $$
begin
  if not exists (select 1 from pg_policies where policyname = 'Public exercises read access') then
    create policy "Public exercises read access" on exercises for select using (true);
  end if;
end
$$;

-- Clear existing data to avoid duplicates on re-run
truncate table exercises;

-- Insert Data
INSERT INTO exercises (id, name, equipment, category, muscle_group) VALUES
('ex-1', 'Barbell Bench Press', 'Barbell', 'Push', 'Chest'),
('ex-2', 'Dumbbells Bench Press', 'Dumbbells', 'Push', 'Chest'),
('ex-3', 'Machine Bench Press', 'Machine', 'Push', 'Chest'),
('ex-4', 'Smith Machine Bench Press', 'Smith Machine', 'Push', 'Chest'),
('ex-5', 'Bands Bench Press', 'Bands', 'Push', 'Chest'),
('ex-6', 'Barbell Incline Bench Press', 'Barbell', 'Push', 'Chest'),
('ex-7', 'Dumbbells Incline Bench Press', 'Dumbbells', 'Push', 'Chest'),
('ex-8', 'Machine Incline Bench Press', 'Machine', 'Push', 'Chest'),
('ex-9', 'Smith Machine Incline Bench Press', 'Smith Machine', 'Push', 'Chest'),
('ex-10', 'Bands Incline Bench Press', 'Bands', 'Push', 'Chest'),
('ex-11', 'Barbell Decline Bench Press', 'Barbell', 'Push', 'Chest'),
('ex-12', 'Dumbbells Decline Bench Press', 'Dumbbells', 'Push', 'Chest'),
('ex-13', 'Machine Decline Bench Press', 'Machine', 'Push', 'Chest'),
('ex-14', 'Smith Machine Decline Bench Press', 'Smith Machine', 'Push', 'Chest'),
('ex-15', 'Barbell Floor Press', 'Barbell', 'Push', 'Chest'),
('ex-16', 'Dumbbells Floor Press', 'Dumbbells', 'Push', 'Chest'),
('ex-17', 'Kettlebell Floor Press', 'Kettlebell', 'Push', 'Chest'),
('ex-18', 'Smith Machine Floor Press', 'Smith Machine', 'Push', 'Chest'),
('ex-19', 'Barbell Overhead Press', 'Barbell', 'Push', 'Shoulders'),
('ex-20', 'Dumbbells Overhead Press', 'Dumbbells', 'Push', 'Shoulders'),
('ex-21', 'Kettlebell Overhead Press', 'Kettlebell', 'Push', 'Shoulders'),
('ex-22', 'Machine Overhead Press', 'Machine', 'Push', 'Shoulders'),
('ex-23', 'Smith Machine Overhead Press', 'Smith Machine', 'Push', 'Shoulders'),
('ex-24', 'Bands Overhead Press', 'Bands', 'Push', 'Shoulders'),
('ex-25', 'Plate Overhead Press', 'Plate', 'Push', 'Shoulders'),
('ex-26', 'Dumbbells Arnold Press', 'Dumbbells', 'Push', 'Shoulders'),
('ex-27', 'Kettlebell Arnold Press', 'Kettlebell', 'Push', 'Shoulders'),
('ex-28', 'Bodyweight Push-ups', 'Bodyweight', 'Push', 'Chest'),
('ex-29', 'Bands Push-ups', 'Bands', 'Push', 'Chest'),
('ex-30', 'Weighted Vest Push-ups', 'Weighted Vest', 'Push', 'Chest'),
('ex-31', 'Decline Push-ups', 'Decline', 'Push', 'Chest'),
('ex-32', 'Incline Push-ups', 'Incline', 'Push', 'Chest'),
('ex-33', 'Bodyweight Dips', 'Bodyweight', 'Push', 'Triceps'),
('ex-34', 'Weighted Dips', 'Weighted', 'Push', 'Triceps'),
('ex-35', 'Machine Dips', 'Machine', 'Push', 'Triceps'),
('ex-36', 'Dip Station Dips', 'Dip Station', 'Push', 'Triceps'),
('ex-37', 'Bench Dips', 'Bench', 'Push', 'Triceps'),
('ex-38', 'Dumbbells Chest Flys', 'Dumbbells', 'Push', 'Chest'),
('ex-39', 'Cables Chest Flys', 'Cables', 'Push', 'Chest'),
('ex-40', 'Machine Chest Flys', 'Machine', 'Push', 'Chest'),
('ex-41', 'Bands Chest Flys', 'Bands', 'Push', 'Chest'),
('ex-42', 'Pec Deck Chest Flys', 'Pec Deck', 'Push', 'Chest'),
('ex-43', 'Dumbbells Lateral Raises', 'Dumbbells', 'Push', 'Shoulders'),
('ex-44', 'Cables Lateral Raises', 'Cables', 'Push', 'Shoulders'),
('ex-45', 'Bands Lateral Raises', 'Bands', 'Push', 'Shoulders'),
('ex-46', 'Machine Lateral Raises', 'Machine', 'Push', 'Shoulders'),
('ex-47', 'Plate Lateral Raises', 'Plate', 'Push', 'Shoulders'),
('ex-48', 'Kettlebell Lateral Raises', 'Kettlebell', 'Push', 'Shoulders'),
('ex-49', 'Dumbbells Front Raises', 'Dumbbells', 'Push', 'Shoulders'),
('ex-50', 'Barbell Front Raises', 'Barbell', 'Push', 'Shoulders'),
('ex-51', 'Plate Front Raises', 'Plate', 'Push', 'Shoulders'),
('ex-52', 'Cables Front Raises', 'Cables', 'Push', 'Shoulders'),
('ex-53', 'Bands Front Raises', 'Bands', 'Push', 'Shoulders'),
('ex-54', 'Kettlebell Front Raises', 'Kettlebell', 'Push', 'Shoulders'),
('ex-55', 'Dumbbells Rear Delt Flys', 'Dumbbells', 'Push', 'Shoulders'),
('ex-56', 'Cables Rear Delt Flys', 'Cables', 'Push', 'Shoulders'),
('ex-57', 'Machine Rear Delt Flys', 'Machine', 'Push', 'Shoulders'),
('ex-58', 'Bands Rear Delt Flys', 'Bands', 'Push', 'Shoulders'),
('ex-59', 'Barbell Upright Rows', 'Barbell', 'Push', 'Shoulders'),
('ex-60', 'Dumbbells Upright Rows', 'Dumbbells', 'Push', 'Shoulders'),
('ex-61', 'Cables Upright Rows', 'Cables', 'Push', 'Shoulders'),
('ex-62', 'Smith Machine Upright Rows', 'Smith Machine', 'Push', 'Shoulders'),
('ex-63', 'Bands Upright Rows', 'Bands', 'Push', 'Shoulders'),
('ex-64', 'Dumbbells Tricep Extensions', 'Dumbbells', 'Push', 'Triceps'),
('ex-65', 'Cables Tricep Extensions', 'Cables', 'Push', 'Triceps'),
('ex-66', 'Barbell Tricep Extensions', 'Barbell', 'Push', 'Triceps'),
('ex-67', 'Bands Tricep Extensions', 'Bands', 'Push', 'Triceps'),
('ex-68', 'Machine Tricep Extensions', 'Machine', 'Push', 'Triceps'),
('ex-69', 'Barbell Skullcrushers', 'Barbell', 'Push', 'Triceps'),
('ex-70', 'Dumbbells Skullcrushers', 'Dumbbells', 'Push', 'Triceps'),
('ex-71', 'EZ Bar Skullcrushers', 'EZ Bar', 'Push', 'Triceps'),
('ex-72', 'Cables Skullcrushers', 'Cables', 'Push', 'Triceps'),
('ex-73', 'Cables Tricep Pushdowns', 'Cables', 'Push', 'Triceps'),
('ex-74', 'Bands Tricep Pushdowns', 'Bands', 'Push', 'Triceps'),
('ex-75', 'Dumbbells Tricep Kickbacks', 'Dumbbells', 'Push', 'Triceps'),
('ex-76', 'Cables Tricep Kickbacks', 'Cables', 'Push', 'Triceps'),
('ex-77', 'Bands Tricep Kickbacks', 'Bands', 'Push', 'Triceps'),
('ex-78', 'Barbell Close Grip Bench Press', 'Barbell', 'Push', 'Triceps'),
('ex-79', 'Smith Machine Close Grip Bench Press', 'Smith Machine', 'Push', 'Triceps'),
('ex-80', 'Dumbbells Close Grip Bench Press', 'Dumbbells', 'Push', 'Triceps'),
('ex-81', 'Pull-up Bar Pull-ups', 'Pull-up Bar', 'Pull', 'Back'),
('ex-82', 'Assisted Machine Pull-ups', 'Assisted Machine', 'Pull', 'Back'),
('ex-83', 'Weighted Pull-ups', 'Weighted', 'Pull', 'Back'),
('ex-84', 'Pull-up Bar Chin-ups', 'Pull-up Bar', 'Pull', 'Back'),
('ex-85', 'Assisted Machine Chin-ups', 'Assisted Machine', 'Pull', 'Back'),
('ex-86', 'Weighted Chin-ups', 'Weighted', 'Pull', 'Back'),
('ex-87', 'Barbell Bent Over Rows', 'Barbell', 'Pull', 'Back'),
('ex-88', 'Dumbbells Bent Over Rows', 'Dumbbells', 'Pull', 'Back'),
('ex-89', 'Kettlebell Bent Over Rows', 'Kettlebell', 'Pull', 'Back'),
('ex-90', 'Smith Machine Bent Over Rows', 'Smith Machine', 'Pull', 'Back'),
('ex-91', 'Bands Bent Over Rows', 'Bands', 'Pull', 'Back'),
('ex-92', 'T-Bar Bent Over Rows', 'T-Bar', 'Pull', 'Back'),
('ex-93', 'Cable Lat Pulldowns', 'Cable', 'Pull', 'Back'),
('ex-94', 'Machine Lat Pulldowns', 'Machine', 'Pull', 'Back'),
('ex-95', 'Bands Lat Pulldowns', 'Bands', 'Pull', 'Back'),
('ex-96', 'Cable Seated Rows', 'Cable', 'Pull', 'Back'),
('ex-97', 'Machine Seated Rows', 'Machine', 'Pull', 'Back'),
('ex-98', 'Bands Seated Rows', 'Bands', 'Pull', 'Back'),
('ex-99', 'Cable Face Pulls', 'Cable', 'Pull', 'Rear Delts'),
('ex-100', 'Bands Face Pulls', 'Bands', 'Pull', 'Rear Delts'),
('ex-101', 'Barbell Bicep Curls', 'Barbell', 'Pull', 'Biceps'),
('ex-102', 'Dumbbells Bicep Curls', 'Dumbbells', 'Pull', 'Biceps'),
('ex-103', 'Cables Bicep Curls', 'Cables', 'Pull', 'Biceps'),
('ex-104', 'Bands Bicep Curls', 'Bands', 'Pull', 'Biceps'),
('ex-105', 'EZ Bar Bicep Curls', 'EZ Bar', 'Pull', 'Biceps'),
('ex-106', 'Machine Bicep Curls', 'Machine', 'Pull', 'Biceps'),
('ex-107', 'Plate Bicep Curls', 'Plate', 'Pull', 'Biceps'),
('ex-108', 'Dumbbells Hammer Curls', 'Dumbbells', 'Pull', 'Biceps'),
('ex-109', 'Cables Hammer Curls', 'Cables', 'Pull', 'Biceps'),
('ex-110', 'Bands Hammer Curls', 'Bands', 'Pull', 'Biceps'),
('ex-111', 'Rope Hammer Curls', 'Rope', 'Pull', 'Biceps'),
('ex-112', 'Barbell Preacher Curls', 'Barbell', 'Pull', 'Biceps'),
('ex-113', 'Dumbbells Preacher Curls', 'Dumbbells', 'Pull', 'Biceps'),
('ex-114', 'Machine Preacher Curls', 'Machine', 'Pull', 'Biceps'),
('ex-115', 'EZ Bar Preacher Curls', 'EZ Bar', 'Pull', 'Biceps'),
('ex-116', 'Dumbbells Concentration Curls', 'Dumbbells', 'Pull', 'Biceps'),
('ex-117', 'Kettlebell Concentration Curls', 'Kettlebell', 'Pull', 'Biceps'),
('ex-118', 'Barbell Shrugs', 'Barbell', 'Pull', 'Traps'),
('ex-119', 'Dumbbells Shrugs', 'Dumbbells', 'Pull', 'Traps'),
('ex-120', 'Smith Machine Shrugs', 'Smith Machine', 'Pull', 'Traps'),
('ex-121', 'Trap Bar Shrugs', 'Trap Bar', 'Pull', 'Traps'),
('ex-122', 'Cables Shrugs', 'Cables', 'Pull', 'Traps'),
('ex-123', 'Plate Shrugs', 'Plate', 'Pull', 'Traps'),
('ex-124', 'Barbell Deadlift', 'Barbell', 'Pull', 'Back'),
('ex-125', 'Trap Bar Deadlift', 'Trap Bar', 'Pull', 'Back'),
('ex-126', 'Dumbbells Deadlift', 'Dumbbells', 'Pull', 'Back'),
('ex-127', 'Kettlebell Deadlift', 'Kettlebell', 'Pull', 'Back'),
('ex-128', 'Smith Machine Deadlift', 'Smith Machine', 'Pull', 'Back'),
('ex-129', 'Dumbbells Single Arm Row', 'Dumbbells', 'Pull', 'Back'),
('ex-130', 'Kettlebell Single Arm Row', 'Kettlebell', 'Pull', 'Back'),
('ex-131', 'Cable Single Arm Row', 'Cable', 'Pull', 'Back'),
('ex-132', 'Machine Single Arm Row', 'Machine', 'Pull', 'Back'),
('ex-133', 'Dumbbell Pullover', 'Dumbbell', 'Pull', 'Back'),
('ex-134', 'Barbell Pullover', 'Barbell', 'Pull', 'Back'),
('ex-135', 'Cable Pullover', 'Cable', 'Pull', 'Back'),
('ex-136', 'Machine Pullover', 'Machine', 'Pull', 'Back'),
('ex-137', 'Barbell Good Mornings', 'Barbell', 'Pull', 'Back'),
('ex-138', 'Bands Good Mornings', 'Bands', 'Pull', 'Back'),
('ex-139', 'Smith Machine Good Mornings', 'Smith Machine', 'Pull', 'Back'),
('ex-140', 'Bodyweight Hyperextensions', 'Bodyweight', 'Pull', 'Back'),
('ex-141', 'Weighted Hyperextensions', 'Weighted', 'Pull', 'Back'),
('ex-142', 'Machine Hyperextensions', 'Machine', 'Pull', 'Back'),
('ex-143', 'Barbell Squat', 'Barbell', 'Legs', 'Quads'),
('ex-144', 'Dumbbells Squat', 'Dumbbells', 'Legs', 'Quads'),
('ex-145', 'Kettlebell Squat', 'Kettlebell', 'Legs', 'Quads'),
('ex-146', 'Smith Machine Squat', 'Smith Machine', 'Legs', 'Quads'),
('ex-147', 'Bodyweight Squat', 'Bodyweight', 'Legs', 'Quads'),
('ex-148', 'Bands Squat', 'Bands', 'Legs', 'Quads'),
('ex-149', 'Safety Bar Squat', 'Safety Bar', 'Legs', 'Quads'),
('ex-150', 'Barbell Front Squat', 'Barbell', 'Legs', 'Quads'),
('ex-151', 'Dumbbells Front Squat', 'Dumbbells', 'Legs', 'Quads'),
('ex-152', 'Kettlebell Front Squat', 'Kettlebell', 'Legs', 'Quads'),
('ex-153', 'Smith Machine Front Squat', 'Smith Machine', 'Legs', 'Quads'),
('ex-154', 'Bodyweight Lunges', 'Bodyweight', 'Legs', 'Legs'),
('ex-155', 'Dumbbells Lunges', 'Dumbbells', 'Legs', 'Legs'),
('ex-156', 'Barbell Lunges', 'Barbell', 'Legs', 'Legs'),
('ex-157', 'Kettlebell Lunges', 'Kettlebell', 'Legs', 'Legs'),
('ex-158', 'Smith Machine Lunges', 'Smith Machine', 'Legs', 'Legs'),
('ex-159', 'Sandbag Lunges', 'Sandbag', 'Legs', 'Legs'),
('ex-160', 'Bodyweight Reverse Lunges', 'Bodyweight', 'Legs', 'Legs'),
('ex-161', 'Dumbbells Reverse Lunges', 'Dumbbells', 'Legs', 'Legs'),
('ex-162', 'Barbell Reverse Lunges', 'Barbell', 'Legs', 'Legs'),
('ex-163', 'Kettlebell Reverse Lunges', 'Kettlebell', 'Legs', 'Legs'),
('ex-164', 'Smith Machine Reverse Lunges', 'Smith Machine', 'Legs', 'Legs'),
('ex-165', 'Bodyweight Side Lunges', 'Bodyweight', 'Legs', 'Legs'),
('ex-166', 'Dumbbells Side Lunges', 'Dumbbells', 'Legs', 'Legs'),
('ex-167', 'Kettlebell Side Lunges', 'Kettlebell', 'Legs', 'Legs'),
('ex-168', 'Bodyweight Bulgarian Split Squat', 'Bodyweight', 'Legs', 'Legs'),
('ex-169', 'Dumbbells Bulgarian Split Squat', 'Dumbbells', 'Legs', 'Legs'),
('ex-170', 'Barbell Bulgarian Split Squat', 'Barbell', 'Legs', 'Legs'),
('ex-171', 'Kettlebell Bulgarian Split Squat', 'Kettlebell', 'Legs', 'Legs'),
('ex-172', 'Smith Machine Bulgarian Split Squat', 'Smith Machine', 'Legs', 'Legs'),
('ex-173', 'Bodyweight Step-ups', 'Bodyweight', 'Legs', 'Legs'),
('ex-174', 'Dumbbells Step-ups', 'Dumbbells', 'Legs', 'Legs'),
('ex-175', 'Barbell Step-ups', 'Barbell', 'Legs', 'Legs'),
('ex-176', 'Kettlebell Step-ups', 'Kettlebell', 'Legs', 'Legs'),
('ex-177', 'Box Step-ups', 'Box', 'Legs', 'Legs'),
('ex-178', 'Machine Leg Press', 'Machine', 'Legs', 'Legs'),
('ex-179', 'Machine Hack Squat', 'Machine', 'Legs', 'Quads'),
('ex-180', 'Barbell Hack Squat', 'Barbell', 'Legs', 'Quads'),
('ex-181', 'Machine Leg Extensions', 'Machine', 'Legs', 'Quads'),
('ex-182', 'Bands Leg Extensions', 'Bands', 'Legs', 'Quads'),
('ex-183', 'Machine Leg Curls', 'Machine', 'Legs', 'Hamstrings'),
('ex-184', 'Bands Leg Curls', 'Bands', 'Legs', 'Hamstrings'),
('ex-185', 'Dumbbell Leg Curls', 'Dumbbell', 'Legs', 'Hamstrings'),
('ex-186', 'Slider Leg Curls', 'Slider', 'Legs', 'Hamstrings'),
('ex-187', 'Barbell Romanian Deadlift', 'Barbell', 'Legs', 'Hamstrings'),
('ex-188', 'Dumbbells Romanian Deadlift', 'Dumbbells', 'Legs', 'Hamstrings'),
('ex-189', 'Kettlebell Romanian Deadlift', 'Kettlebell', 'Legs', 'Hamstrings'),
('ex-190', 'Smith Machine Romanian Deadlift', 'Smith Machine', 'Legs', 'Hamstrings'),
('ex-191', 'Bands Romanian Deadlift', 'Bands', 'Legs', 'Hamstrings'),
('ex-192', 'Trap Bar Romanian Deadlift', 'Trap Bar', 'Legs', 'Hamstrings'),
('ex-193', 'Bodyweight Calf Raises', 'Bodyweight', 'Legs', 'Calves'),
('ex-194', 'Dumbbells Calf Raises', 'Dumbbells', 'Legs', 'Calves'),
('ex-195', 'Barbell Calf Raises', 'Barbell', 'Legs', 'Calves'),
('ex-196', 'Machine Calf Raises', 'Machine', 'Legs', 'Calves'),
('ex-197', 'Smith Machine Calf Raises', 'Smith Machine', 'Legs', 'Calves'),
('ex-198', 'Leg Press Calf Raises', 'Leg Press', 'Legs', 'Calves'),
('ex-199', 'Bodyweight Glute Bridges', 'Bodyweight', 'Legs', 'Glutes'),
('ex-200', 'Barbell Glute Bridges', 'Barbell', 'Legs', 'Glutes'),
('ex-201', 'Dumbbell Glute Bridges', 'Dumbbell', 'Legs', 'Glutes'),
('ex-202', 'Bands Glute Bridges', 'Bands', 'Legs', 'Glutes'),
('ex-203', 'Machine Glute Bridges', 'Machine', 'Legs', 'Glutes'),
('ex-204', 'Barbell Hip Thrusts', 'Barbell', 'Legs', 'Glutes'),
('ex-205', 'Dumbbell Hip Thrusts', 'Dumbbell', 'Legs', 'Glutes'),
('ex-206', 'Machine Hip Thrusts', 'Machine', 'Legs', 'Glutes'),
('ex-207', 'Smith Machine Hip Thrusts', 'Smith Machine', 'Legs', 'Glutes'),
('ex-208', 'Bands Hip Thrusts', 'Bands', 'Legs', 'Glutes'),
('ex-209', 'Dumbbell Goblet Squat', 'Dumbbell', 'Legs', 'Quads'),
('ex-210', 'Kettlebell Goblet Squat', 'Kettlebell', 'Legs', 'Quads'),
('ex-211', 'Barbell Sumo Squat', 'Barbell', 'Legs', 'Legs'),
('ex-212', 'Dumbbell Sumo Squat', 'Dumbbell', 'Legs', 'Legs'),
('ex-213', 'Kettlebell Sumo Squat', 'Kettlebell', 'Legs', 'Legs'),
('ex-214', 'Smith Machine Sumo Squat', 'Smith Machine', 'Legs', 'Legs'),
('ex-215', 'Bodyweight Plank', 'Bodyweight', 'Core', 'Core'),
('ex-216', 'Weighted Plank', 'Weighted', 'Core', 'Core'),
('ex-217', 'Bodyweight Side Plank', 'Bodyweight', 'Core', 'Core'),
('ex-218', 'Bodyweight Crunches', 'Bodyweight', 'Core', 'Core'),
('ex-219', 'Machine Crunches', 'Machine', 'Core', 'Core'),
('ex-220', 'Cable Crunches', 'Cable', 'Core', 'Core'),
('ex-221', 'Ball Crunches', 'Ball', 'Core', 'Core'),
('ex-222', 'Bodyweight Sit-ups', 'Bodyweight', 'Core', 'Core'),
('ex-223', 'Weighted Sit-ups', 'Weighted', 'Core', 'Core'),
('ex-224', 'Decline Bench Sit-ups', 'Decline Bench', 'Core', 'Core'),
('ex-225', 'Bodyweight Leg Raises', 'Bodyweight', 'Core', 'Core'),
('ex-226', 'Pull-up Bar Leg Raises', 'Pull-up Bar', 'Core', 'Core'),
('ex-227', 'Dip Station Leg Raises', 'Dip Station', 'Core', 'Core'),
('ex-228', 'Bench Leg Raises', 'Bench', 'Core', 'Core'),
('ex-229', 'Bodyweight Russian Twists', 'Bodyweight', 'Core', 'Core'),
('ex-230', 'Dumbbell Russian Twists', 'Dumbbell', 'Core', 'Core'),
('ex-231', 'Kettlebell Russian Twists', 'Kettlebell', 'Core', 'Core'),
('ex-232', 'Plate Russian Twists', 'Plate', 'Core', 'Core'),
('ex-233', 'Ball Russian Twists', 'Ball', 'Core', 'Core'),
('ex-234', 'Bodyweight Mountain Climbers', 'Bodyweight', 'Core', 'Core'),
('ex-235', 'Sliders Mountain Climbers', 'Sliders', 'Core', 'Core'),
('ex-236', 'Bodyweight Bicycle Crunches', 'Bodyweight', 'Core', 'Core'),
('ex-237', 'Ab Wheel Ab Rollouts', 'Ab Wheel', 'Core', 'Core'),
('ex-238', 'Barbell Ab Rollouts', 'Barbell', 'Core', 'Core'),
('ex-239', 'Bodyweight Burpees', 'Bodyweight', 'Full Body', 'Full Body'),
('ex-240', 'Bodyweight Jumping Jacks', 'Bodyweight', 'Cardio', 'Full Body'),
('ex-241', 'Kettlebell Kettlebell Swings', 'Kettlebell', 'Full Body', 'Full Body'),
('ex-242', 'Dumbbell Kettlebell Swings', 'Dumbbell', 'Full Body', 'Full Body'),
('ex-243', 'Jump Rope Jump Rope', 'Jump Rope', 'Cardio', 'Legs'),
('ex-244', 'Box Box Jumps', 'Box', 'Cardio', 'Legs'),
('ex-245', 'Ropes Battle Ropes', 'Ropes', 'Cardio', 'Full Body');